### PR TITLE
Add python_requires to setup.py

### PR DESCRIPTION
**Pull request by jornh**
Almost too little to warrant a PR, but hey!

### CODE REVIEW

**Comment by jornh** [comment]
Hmm, this has turned into a small Travis setup testing session: https://travis-ci.org/lyft/amundsencommon/builds/574150435#L347

@jinhyukchang got a key 🔑?

**Comment by jinhyukchang** [comment]
> Hmm, this has turned into a small Travis setup testing session: https://travis-ci.org/lyft/amundsencommon/builds/574150435#L347
> 
> @jinhyukchang got a key 🔑?

How did you find this repo already? lol 
Hold on.. I am working with support team enabling Travis. Stay tuned!

**Comment by jornh** [comment]
Lol! With the ping in https://github.com/lyft/amundsen/issues/13#issuecomment-522197074 it wasn’t all too hard.

No worries, I understand working with other teams getting it can take a bit of back and forth. It will come as it can.

Also, as an aside, with the topic tagging on the repos there is now nice(r) navigation across the by now quite many repos. They are never more than 3 clicks away if you e.g.;

- from here click `Code`, `amundsen` (say it out loud and you will never forget ;) then the third click will bring you to any other Amundsen repo!

**Comment by jinhyukchang** [comment]
> Lol! With the ping in [lyft/amundsen#13 (comment)](https://github.com/lyft/amundsen/issues/13#issuecomment-522197074) it wasn’t all too hard.
> 
> No worries, I understand working with other teams getting it can take a bit of back and forth. It will come as it can.
> 
> Also, as an aside, with the topic tagging on the repos there is now nice(r) navigation across the by now quite many repos. They are never more than 3 clicks away if you e.g.;
> 
> * from here click `Code`, `amundsen` (say it out loud and you will never forget ;) then the third click will bring you to any other Amundsen repo!

Hey @jornh ,
Just completed Travis integration. Can you try it out one more time?

I like the idea of having a submodule back to `amundsen`. Will do that :)

**Comment by jornh** [comment]
@jinhyukchang green build!

**Pull request merged**
